### ISSUE TITLE
Trying the Demo - It is asking for openAIApiKey but that's not in the instructions

### ISSUE THREAD

**Issue by KristinBethea** [Azure-Samples/azure-search-openai-demo-csharp#322] opened 2024-05-21 19:48 UTC
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [X ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>
azd auth login 
azd up
environment name 
Subscription
Location
then it asks for 
Enter a value for the 'openAIApiKey' infrastructure parameter:
but nothing in the documetation for this

### Any log messages given by the failure
>
The Help option doesn't tell me anything other than 
Hint: OpenAI API Key

### Expected/desired behavior
>
Move on to the next step of the demo

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)
Windows 11 Pro

### Versions
>
23H2
### Mention any other details that might be useful
Please help me!
I'm so excited to learn AI!
My company really REALLY needs me to learn all this. 
Thanks!
> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by lgmorand** [comment] 2024-05-22 19:21
dupe of #318 

@KristinBethea  please close this issue :)

**Closed** 2024-05-22 19:34 UTC
